mysql:
  test:               #键名,Db() 等价于 Db("default")
    host: 127.0.0.1     #数据库host或ip
    port: 3306           #端口号
    database: test       #数据库名
    username: root1       #账号
    password: 123456           #密码
    charset: utf8mb4     #字符集
    loglevel: info       #info,warn,error,silent，默认为warn
    parsetime: true      #设置了会正确处理time.time类型
    location: Local      #时区
    tableprefix:         #表前缀
    singulartable: true  #是否使用单数表名
    skipdefaulttransaction: true #是否禁止默认事务,为了确保数据一致性，GORM 会在事务里执行写入操作（创建、更新、删除），默认为true,
    slowthreshold: 100   #慢查询阈值,单位毫秒,默认为100ms
    disableautomaticping: false #是否禁止自动ping,默认为false
    allowglobalupdate: false #启用全局 update/delete, 默认为false
    maxidleconns: 300 #设置空闲连接池中连接的最大数量 gorm使用database/sql包维护连接池 【建议设置】maxidleconns <= maxopenconns
    maxopenconns: 300 #设置打开数据库连接的最大数量 【建议设置】
    connmaxlifetime: 600 #设置连接可复用的最大时间，即链接的最长生命周期,单位秒,0则不过期【建议设置】
    connmaxidletime: 550s #设置连接空闲最大等待时间,0则不过期，需小于connmaxlifetime
    writeTimeout: 1s  #设置写超时
    readtimeout: 1s  #设置读超时
    timeout: 1s  #设置连接超时
    ignorerecordnotfounderror: true #设置是否忽略记录不存在错误，建议设置为true